import "./globals.css";
import Image from "next/image";
import NewsLogo from "./NewsLogo.png";

export const metadata = {
  title: "Everything Philippines",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="navbar">
          <ul>
            <li className="logo">
              <Image src={NewsLogo} alt="News Logo" width={50} height={50} />
            </li>
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/sports">Sports</a>
            </li>
            <li>
              <a href="/business">Business</a>
            </li>
            <li>
              <a href="/lifestyle">Lifestyle</a>
            </li>
          </ul>
        </nav>
        {children}
        <footer>
          <p>
            <a
              href="https://www.feedspot.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by Feedspot RSS Reader
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
