import "./globals.css";
import Navbar from "./components/navbar";

export const metadata = {
  title: "Everything Philippines",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <footer>
          <p>
            <a
              href="https://www.feedspot.com/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by Feedspot RSS Reader
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
